pipeline:
    name: CI Pipeline
    identifier: CI_Pipeline
    projectIdentifier: Harness01
    orgIdentifier: default
    tags: {}
    properties:
        ci:
            codebase:
                connectorRef: account.MyGitConnector
                repoName: goHelloWorldServer
                build: <+input>
    stages:
        - stage:
              name: Build Test and Push
              identifier: Build_Test_and_Push
              description: ""
              type: CI
              spec:
                  cloneCodebase: true
                  infrastructure:
                      type: KubernetesDirect
                      spec:
                          connectorRef: account.EKSAWSConnector
                          namespace: ng-ci-build-farm
                  execution:
                      steps:
                          - step:
                                type: Run
                                name: Run Unit Tests
                                identifier: Run_Unit_Tests
                                spec:
                                    connectorRef: account.DockerRegConnector
                                    image: golang:1.15
                                    command: |-
                                        go get gotest.tools/gotestsum
                                        gotestsum --format=standard-verbose --junitfile unit-tests.xml || true
                                        CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -a -tags netgo
                                    privileged: false
                          - step:
                                type: BuildAndPushDockerRegistry
                                name: Build and push image to DockerHub
                                identifier: Build_and_push_image_to_DockerHub
                                spec:
                                    connectorRef: account.DockerRegConnector
                                    repo: aslabs/ci-build-go
                                    tags:
                                        - <+pipeline.sequenceId>
                                    optimize: true
              variables: []
